env:
  browser: true
  es6: true
  node: true
  'googleappsscript/googleappsscript': true
  'jest/globals': true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended

plugins:
  - googleappsscript

rules:
  '@typescript-eslint/explicit-function-return-type':
    - warn
    - allowExpressions: true
