name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - uses: actions/checkout@v2

      - name: Use npm cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ env.cache-name }}-
            ${{ runner.os }}-npm-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --ci --coverage

      - name: Build
        run: npm run build

      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - if: github.ref == 'refs/heads/master'
        name: Deploy
        run: echo $CLASPRC > ~/.clasprc.json && npm run deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
