name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --ci --coverage

      - name: Build
        run: npm run build

      - if: github.ref == 'refs/heads/master'
        name: Deploy
        run: echo "$CLASPRC" > ~/.clasprc.json && npm run deploy
        env:
          CLASPRC: ${{ secrets.CLASPRC }}
