name: Merge

on:
  workflow_run:
    types:
      - completed
    workflows:
      - Pull Request Auto Review

jobs:
  merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Merge
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: dependabot-preview
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_GITHUB_API_PREVIEW: true
          MERGE_METHOD: SQUASH
